### ISSUE TITLE
Attempting to remove "?viasf=1" from downloaded files but "No such file or directory" error message.  

### ISSUE THREAD

**Issue by fsword7** [SpiritQuaddicted/sourceforge-file-download#8]
I attempted to download files from sourceforge but I got error messages trying remove "?viasf=1" from downloaded files. 

# remove ?viasf=1 suffix
find . -name '*?viasf=1' -print0 | xargs -0 rename --verbose "?viasf=1" ""

I got error message said:

xargs: rename: No such file or directory

I am using Ubuntu 23.10 distro.

Thanks,
Tim

**Comment by SpiritQuaddicted** [comment]
You need a `rename` tool. Try `apt install util-linux`.

**Comment by fsword7** [comment]
Ok, I now got it.  For Ubuntu system, 'util-linux' was already installed but I now did 'apt install rename'. 

I tried it but it did not work. Rename gave me syntax error.   I changed a line:

find . -name '*?viasf=1' -exec rename -v "s/\?viasf=1//" {} \;

After I changed it, everything worked now. 

Thanks again,
Tim

**Comment by SpiritQuaddicted** [comment]
Ah, weird! Thank you for posting the solution :)
I hope the script works well for you now.
